module.exports = {
  INIT_LOBBY: 'INIT_LOBBY',
  INIT_GAME: 'INIT_GAME',
  CHAT_MESSAGE_RECEIVED: 'CHAT_MESSAGE_RECEIVED',
  PLAYERS_JOINED: 'PLAYERS_JOINED',
  PLAYERS_LEFT: 'PLAYERS_LEFT',

  JOIN_GAME: 'JOIN_GAME',
  SEND_MESSAGE: 'SEND_MESSAGE',

  DISCONNECT: 'disconnect',
  CONNECT: 'CONNECT'
};
